
**Практика. Классификация русскоязычного текста.**
---



Датасет:


https://www.kaggle.com/datasets/serart/nti-news-text-seriescsv

1. Выбрать 3 любых класса новостей
2. Создать эмбединги bge-m3
3. Создать модель классификации с помощью кода из прошлого занятия
4. Посчитать метрику accuracy
5. Визуализировать распределение слов по классам. 3 любых топика новостей *


Эмбеддинги BGE-M3:
https://huggingface.co/BAAI/bge-m3

Датасет: https://drive.google.com/file/d/1Jh4lynfimzAm9-OTEmKZaUDkP466z95X/view?usp=sharing

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

In [ ]:
data_news = pd.read_csv('/content/drive/MyDrive/Dataset/text_series_full.csv')

In [ ]:
data_news

Unnamed: 0                                               text  \
0                0  трамп клинтон выиграли праймериз аризоне проиг...   
1                1  Госдума утвердила введение присяги вступлении ...   
2                2  черная дыра роскосмоса откуда берутся заоблачн...   
3                3  уганде родители пытались убить дочь переход ис...   
4                4  Белгородский захватчик банка получил года коло...   
...            ...                                                ...   
408341      409150  пущино бийск сохранить положение наукоградов г...   
408342      409151  лента выживший ди каприо базовый роль выходить...   
408343      409152  туркменгаз подтверждает готовность вести перег...   
408344      409153  дагестан япония производить горючее нового пок...   
408345      409154  зачинатель кирилл провести рождественский теле...   

        is_train     class  
0           True     world  
1           True  politics  
2           True  politics  
3           True  religion  
4           True  politics  
...          ...       ...  
408341     False       NaN  
408342     False       NaN  
408343     False       NaN  
408344     False       NaN  
408345     False       NaN  

[408346 rows x 4 columns]

In [ ]:
data_news.dropna(inplace = True)

In [ ]:
data_news

Unnamed: 0                                               text  \
0                0  трамп клинтон выиграли праймериз аризоне проиг...   
1                1  Госдума утвердила введение присяги вступлении ...   
2                2  черная дыра роскосмоса откуда берутся заоблачн...   
3                3  уганде родители пытались убить дочь переход ис...   
4                4  Белгородский захватчик банка получил года коло...   
...            ...                                                ...   
407579      408388  американцы вновь выдали новость бородой марсе ...   
407580      408389  Появилось видео вскрытия гроба Иисуса Христа В...   
407581      408390  дремов погиб отлучившись свадьбы служебным дел...   
407582      408391  Курды подготовились штурму столицы Исламского ...   
407583      408392  иран даст возможность магатэ изучить объект ку...   

        is_train     class  
0           True     world  
1           True  politics  
2           True  politics  
3           True  religion  
4           True  politics  
...          ...       ...  
407579      True   science  
407580      True   science  
407581      True  politics  
407582      True     world  
407583      True     world  

[407584 rows x 4 columns]

In [ ]:
data_news['class'].value_counts()

class
world       162184
politics    113942
society      51555
science      45519
religion     22518
culture       6610
economy       5256
Name: count, dtype: int64

In [ ]:
df_data = data_news[['text', 'class']][(data_news['class']=='society')|(data_news['class']=='religion')|(data_news['class']=='economy')]

In [ ]:
data_4k = df_data.sample(frac = 0.1, random_state=10)

In [ ]:
data_4k['class'].value_counts()

class
society     5213
religion    2212
economy      508
Name: count, dtype: int64

In [ ]:
from sklearn.utils import resample

In [ ]:
data_4k[data_4k['class']=='society']

text    class
132533  интернет шоке телепузики победили трампа медве...  society
56612   побег школы большинство учителеи хотели сменит...  society
3683    туристку украины арестовали абудаби секс брака...  society
333804  пугачева метнула букет невесты традиции прицеп...  society
299759  лишили газировки раньше вологда знаменита весь...  society
...                                                   ...      ...
26877   лето дача остеохондроз лечим поясницу сквозняк...  society
268650  адвокаты отправивший русского хокинга сизо суд...  society
199839  Недоброжелатели выложили сеть интимные фото эс...  society
218156  абоненты tele смогут покататься гумкатке беспл...  society
353936  пермскому люциферу подарили братика супруговса...  society

[5213 rows x 2 columns]

In [ ]:
data_downsampled = pd.concat([data_4k[data_4k['class']=='society'][0:500],
                              data_4k[data_4k['class']=='religion'][0:500],
                               data_4k[data_4k['class']=='economy']])

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("BAAI/bge-m3")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/15.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

1_Pooling%2Fconfig.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

In [ ]:
model.encode('Привет как дела?')

array([-0.01082552,  0.03332983, -0.05095183, ..., -0.00783309,
       -0.00808375,  0.01319165], dtype=float32)

In [ ]:
from tqdm import tqdm
embeddings = []
for i in tqdm(range(len(data_downsampled))):
    embeddings.append(model.encode(df_data.text.iloc[i]))

100%|██████████| 1508/1508 [03:47<00:00,  6.63it/s]


In [ ]:
embeddings[0].shape

(1024,)

In [ ]:
data_4k = data_downsampled

In [ ]:
data_4k['class'].replace('religion', 0, inplace = True)
data_4k['class'].replace('society', 1, inplace = True)
data_4k['class'].replace('economy', 2, inplace = True)

In [ ]:
import numpy as np

In [ ]:
np.array(data_4k['class'])

array([1, 1, 1, ..., 2, 2, 2])

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split

In [ ]:
import torch
from torch.utils.data import DataLoader, TensorDataset

# Пример: эмбеддинги и метки
embeddings = torch.tensor(embeddings) # 153164 samples, 384-dimensional embeddings


<ipython-input-34-dfbd848fab8f>:5: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:278.)
  embeddings = torch.tensor(embeddings) # 153164 samples, 384-dimensional embeddings


In [ ]:
labels = torch.nn.functional.one_hot(torch.tensor(np.array(data_4k['class'])),
                                     num_classes=3)

In [ ]:
np.array(data_4k['class'])

array([1, 1, 1, ..., 2, 2, 2])

In [ ]:
len(embeddings)

1508

In [ ]:
labels

tensor([[0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        ...,
        [0, 0, 1],
        [0, 0, 1],
        [0, 0, 1]])

In [ ]:
embeddings

tensor([[ 0.0203,  0.0232, -0.0310,  ..., -0.0046, -0.0029, -0.0147],
        [-0.0223, -0.0040, -0.0272,  ..., -0.0414, -0.0092, -0.0014],
        [-0.0213, -0.0163, -0.0281,  ..., -0.0199,  0.0008,  0.0133],
        ...,
        [-0.0394, -0.0137, -0.0095,  ...,  0.0022, -0.0184, -0.0134],
        [-0.0174, -0.0208, -0.0362,  ...,  0.0172, -0.0360,  0.0107],
        [ 0.0105,  0.0110, -0.0405,  ..., -0.0217, -0.0036, -0.0137]])

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class TextClassifier(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_classes):
        super(TextClassifier, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim // 2)
        self.fc3 = nn.Linear(hidden_dim // 2, num_classes)
        self.dropout = nn.Dropout(0.5)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = F.relu(self.fc2(x))
        x = self.dropout(x)
        x = self.fc3(x)
        return x

# Пример использования:
input_dim = 1024  # Размерность эмбеддингов
hidden_dim = 512  # Размерность скрытого слоя
num_classes = 3   # Количество классов

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
device

device(type='cuda')

In [ ]:
model = TextClassifier(input_dim, hidden_dim, num_classes)
print(model)

TextClassifier(
  (fc1): Linear(in_features=1024, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=256, bias=True)
  (fc3): Linear(in_features=256, out_features=3, bias=True)
  (dropout): Dropout(p=0.5, inplace=False)
)


In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
batch_size = 32
input_data = embeddings
labels = torch.from_numpy(np.array(data_4k['class']))

In [ ]:
torch.from_numpy(np.array(data_4k['class']))

tensor([1, 1, 1,  ..., 2, 2, 2])

In [ ]:
# Функция потерь и оптимизатор
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Обучение модели
num_epochs = 10
for epoch in range(num_epochs):
    model.train()  # Переводим модель в режим обучения
    optimizer.zero_grad()

    # Прямой проход
    outputs = model(input_data)
    loss = criterion(outputs, labels)

    # Обратный проход и оптимизация
    loss.backward()
    optimizer.step()

    # Вычисляем accuracy
    model.eval()  # Переводим модель в режим оценки
    with torch.no_grad():
        predictions = torch.argmax(outputs, dim=1)  # Получаем предсказанные классы
        accuracy = accuracy_score(labels.cpu().numpy(), predictions.cpu().numpy())

    # Выводим результаты
    print(f'Epoch {epoch+1}/{num_epochs}, Loss: {loss.item():.4f}, Accuracy: {accuracy:.4f}')

Epoch 1/10, Loss: 1.0986, Accuracy: 0.3309
Epoch 2/10, Loss: 1.0980, Accuracy: 0.3302
Epoch 3/10, Loss: 1.0973, Accuracy: 0.3720
Epoch 4/10, Loss: 1.0967, Accuracy: 0.3753
Epoch 5/10, Loss: 1.0959, Accuracy: 0.3773
Epoch 6/10, Loss: 1.0947, Accuracy: 0.3859
Epoch 7/10, Loss: 1.0932, Accuracy: 0.3999
Epoch 8/10, Loss: 1.0917, Accuracy: 0.4423
Epoch 9/10, Loss: 1.0906, Accuracy: 0.4224
Epoch 10/10, Loss: 1.0865, Accuracy: 0.4755
